"""add_clip_features_table

Revision ID: 0a7b9d13f983
Revises: 54bc018d2b6e
Create Date: 2026-03-29 18:05:56.443161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7b9d13f983'
down_revision: Union[str, None] = '54bc018d2b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('feature_type', sa.String(length=16), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['clip_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_features_candidate_id'), 'clip_features', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clip_features_candidate_id'), table_name='clip_features')
    op.drop_table('clip_features')
    # ### end Alembic commands ###
