"""add_clip_variants_and_feedback

Revision ID: 83e3f160d4fa
Revises: c8fff74a62fa
Create Date: 2026-03-30 08:49:28.059694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83e3f160d4fa'
down_revision: Union[str, None] = 'c8fff74a62fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['clip_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_feedback_candidate_id'), 'clip_feedback', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_clip_feedback_video_id'), 'clip_feedback', ['video_id'], unique=False)
    op.create_table('clip_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('variant_type', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('title_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overlay_text', sa.Text(), nullable=True),
    sa.Column('subtitle_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['clip_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_variants_candidate_id'), 'clip_variants', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clip_variants_candidate_id'), table_name='clip_variants')
    op.drop_table('clip_variants')
    op.drop_index(op.f('ix_clip_feedback_video_id'), table_name='clip_feedback')
    op.drop_index(op.f('ix_clip_feedback_candidate_id'), table_name='clip_feedback')
    op.drop_table('clip_feedback')
    # ### end Alembic commands ###
