"""add_clip_candidates_table

Revision ID: 54bc018d2b6e
Revises: ad2d6c26ba62
Create Date: 2026-03-29 13:38:07.222783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bc018d2b6e'
down_revision: Union[str, None] = 'ad2d6c26ba62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('candidate_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('candidate_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_marker', sa.String(length=64), nullable=True),
    sa.Column('transcript_preview', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_candidates_video_id'), 'clip_candidates', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clip_candidates_video_id'), table_name='clip_candidates')
    op.drop_table('clip_candidates')
    # ### end Alembic commands ###
