"""add_clip_scores_table

Revision ID: c8fff74a62fa
Revises: 0a7b9d13f983
Create Date: 2026-03-30 06:11:01.880940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8fff74a62fa'
down_revision: Union[str, None] = '0a7b9d13f983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('hook_score', sa.Float(), nullable=False),
    sa.Column('retention_score', sa.Float(), nullable=False),
    sa.Column('share_score', sa.Float(), nullable=False),
    sa.Column('packaging_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['clip_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_scores_candidate_id'), 'clip_scores', ['candidate_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clip_scores_candidate_id'), table_name='clip_scores')
    op.drop_table('clip_scores')
    # ### end Alembic commands ###
