"""add_shots_table

Revision ID: 95dc6e206638
Revises: 507a8350e701
Create Date: 2026-03-29 11:19:26.006693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95dc6e206638'
down_revision: Union[str, None] = '507a8350e701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('shot_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('keyframe_path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_video_id'), 'shots', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shots_video_id'), table_name='shots')
    op.drop_table('shots')
    # ### end Alembic commands ###
